version: "3"
services:
  app_python:
    image: thecarrot/whataretime:latest
    build: app_python
    volumes:
      - volume-python:/app/volume
    ports:
      - 5000:8000

volumes:
  volume-python: