FROM python:3.11.3-slim

RUN mkdir /app
COPY ./ /app
WORKDIR /app

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN python -m pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false 
RUN poetry install --no-dev

# RUN adduser app --system -S /bin/nologin -D -H
# USER app

ENV PORT="8000"
EXPOSE $PORT

CMD ["sh", "-c", "/usr/local/bin/python3 -m exec uvicorn src.app:app --host 0.0.0.0 --port $PORT"]