global:
  scrape_interval: 5s


scrape_configs:
  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080
  - job_name: python_app
    static_configs:
      - targets:
          - python_app:8000
  - job_name: typescript_app
    static_configs:
      - targets:
          - typescript_app:5173
