{
 "title": "Loki dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Grafana logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"monitoring-grafana-1\"} | logfmt"
    }
   ]
  },
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"monitoring-loki-1\"} | logfmt"
    }
   ]
  },
  {
   "title": "Promtail logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"monitoring-promtail-1\"} | logfmt"
    }
   ]
  },
  {
   "title": "Python logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"monitoring-time_python-1\"} | logfmt"
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"monitoring-prometheus-1\"} | logfmt"
    }
   ]
  },
  {
   "title": "JS App logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"monitoring-joke_js-1\"}"
    }
   ]
  }
 ]
}