- name: Wipe all from lab 6
  block:
    - name: drop container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
    - name: delete image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        state: absent
  tags:
    - wipe
  when: web_app_full_wipe | bool