- name: go_app
  hosts: all
  become: true
  become_method: 'sudo'
  roles:
    - name: web_app
      tags: [web_app-go]
      vars:
        web_app_name: app_go
        web_app_path: /app_go
        web_app_port: 8070
        web_container_port: 8070
        web_app_image: docker.io/quiner/app-go:latest
