apiVersion: v1
kind: Service
metadata:
  name: app-python-service
spec:
  selector:
    app: app_python
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000
  - name: custom-port
    protocol: TCP
    port: 8080  
    targetPort: 5000
  type: NodePort
