- name: Ping all hosts
  hosts: lab_hosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

- name: Deploy docker
  hosts: lab_hosts
  become: yes
  roles:
    # Run existing docker deployment role
    # installed via ansible-galaxy
    - role: geerlingguy.docker
