- name: Update cache
  apt:
    update_cache: yes

- name: Dependencies installation
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes

- name: Apt key initialization
  apt_key:
    url: "{{ docker_apt_key }}"

- name: Repository initialization
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Docker installation
  apt:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"