scrape_configs:
  - job_name: 'loki_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3100']
  - job_name: 'prometheus_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'promtail_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9080' ]
  - job_name: 'grafana_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:3000' ]
  - job_name: 'python_app_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:80' ]
  - job_name: 'kotlin_app_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:81' ]
