server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push
    tenant_id: docker

scrape_configs:
  - job_name: main
    static_configs:
      - targets:
          - localhost
        labels:
          job: main
          __path__: /var/log/main.log
    pipeline_stages:
      - json:
          expressions:
            http_method: "method"
            http_status: "status"
      - labels:
          http_method:
          http_status:
