{
 "title": "Python app dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"python_app_monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by pages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_view_transport_method_total[$__rate_interval])",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Prometheus requests count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(django_http_requests_total_by_view_transport_method_total{view=\"prometheus-django-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index page requests count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(django_http_requests_total_by_view_transport_method_total{view=\"index\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}