name: Application build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies (primary and developer)
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
          pip install -r app_python/dev-requirements.txt
      - name: Lint with pylint
        run: |
          pylint app_python/app.py
      - name: Test with pytest
        run: |
          pytest app_python/test.py

      - 
        name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.9@master
        with:
          args: --workdir app_python --all-projects -- --allow-missing
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Docker container build and push to registry
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops_inno:latest
