name: C# CI Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app_csharp/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore Dependencies
      run: |
        cd app_csharp
        dotnet restore

    - name: Build
      run: |
        cd app_csharp
        dotnet build --no-restore

    - name: Run Tests
      run: |
        cd app_csharp
        dotnet test --no-build

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk Test
      run: |
        cd app_csharp/app_csharp
        snyk test --all-projects --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        cd app_csharp
        docker build -t dmitriypru/core_course_labs_csharp:latest .
        docker push dmitriypru/core_course_labs_csharp:latest
