name: Kotlin app CI

on:
  push:
    paths:
    - 'app_kotlin/**'
    - '.github/workflows/kotlin-app-ci.yml'
    - '!**.md'
  pull_request:
    paths:
    - 'app_kotlin/**'
    - '.github/workflows/kotlin-app-ci.yml'
    - '!**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    defaults:
      run:
        working-directory: ./app_kotlin/lab1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build dependencies with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Kotlin Linter
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.0/ktlint && chmod a+x ktlint
          ./ktlint
      - name: Run Tests
        run: mvn test
      - name: Install snyk
        uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true # To make sure that SARIF upload gets called
        run: snyk test --severity-threshold=high --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app_kotlin/lab1/snyk.sarif

  push-to-dockerhub:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_kotlin
          file: ./app_kotlin/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_kotlin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
