name: Python package

on:
  push:
    paths:
      - '.github/workflows/python_app.yaml'
      - 'app_python/**'
      - '!app_python/**.md'

defaults:
  run:
    shell: bash
    working-directory: app_python

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Linter
        run: |
          pylint app/main.py

      - name: SNYK install
        run: |
          npm install snyk@latest -g
      - name: Snyk Test
        run: |
          snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Test with pytest
        run: |
          bash -c "(cd app && uvicorn main:app &)"
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops:app-python
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops:app-python-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops:app-python-buildcache,mode=max



