name: CI

on:
  push:
    branches:
      - main
      - lab3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - run: |
          python3 -m pip install --upgrade pip
          cd app_python && (if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; cd ../../)

      - name: Linter
        run: |
          pip install flake8
          flake8

      - name: Tests
        run: 
          cd app_python && (python3 -m unittest test_app.py; cd ../../)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: app_python/
          push: true
          tags: acceptasis/my-python-app:latest
